name: 'Sonar Project Validation'
description: 'Run Sonar and Tests to Validate Quality'

inputs:
  github-repo-name:
    description: 'GitHub repo name'
    required: true
    default: ''
  sonar-tool-version:
    description: 'Sonar tool version'
    required: false
    default: '5.13.0'
  use-dependencies:
    description: 'Use Docker to run dependencies.'
    required: false
    default: false
  docker-compose-file-path:
    description: 'Path to docker compose file to start dependencies'
    required: false
    default: 'docker-compose/test-dependencies-compose.yml'
  github-token:
    description: 'Github Token'
    required: true
  sonar-token:
    description: 'Sonar Token'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  path-to-repo-root:
    description: 'Path to Repo Root'
    required: false
    default: ''
  smoke-runsettings-path:
    description: 'full smoke.runsettings file path.'
    required: false
    default: 'NONE'
  local-runsettings-path:
    description: 'full local.runsettings file path, use NONE when file not required'
    required: false
    default: 'test/local.runsettings'
  upload-sonar-results:
    description: 'Whether to upload Sonar results as an artifact'
    required: false
    default: true
    
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Java Install
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Dotnet Sonar Scanner Install
      run: |
        if dotnet tool list -g | grep -q sonarscanner; then
          echo "Sonar Scanner Already Installed"
        else
          dotnet tool install --global dotnet-sonarscanner --version ${{inputs.sonar-tool-version}}
          echo "Sonar Scanner now installed."
        fi
      shell: bash

    - name: Dotnet Coverage Install
      run: | 
        if dotnet tool list -g | grep -q dotnet-coverage; then
          echo "Dotnet Coverage Already Installed"
        else
          dotnet tool install -g dotnet-coverage
          echo "Dotnet Coverage now installed."
        fi
      shell: bash
        
    - name: Containerized Dependencies
      if: ${{ inputs.use-dependencies == true && inputs.path-to-repo-root  == '' }}
      run: |
        echo "Running docker compose"
        docker-compose -f ${{inputs.docker-compose-file-path}} up -d
      shell: bash

    - name: Containerized Dependencies with Path
      if: ${{ inputs.use-dependencies == true &&  inputs.path-to-repo-root != '' }}
      run: |
        echo "Running docker compose"
        PATH_TO_REPO_ROOT='${{ inputs.path-to-repo-root }}' docker-compose -f ${{ inputs.docker-compose-file-path }} up -d
      shell: bash

    - name: Sonarqube Run
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }} 
      run: |
        export PATH=$PATH:$HOME/.dotnet/tools
        dotnet sonarscanner begin /k:"SynergyDataSystems_${{ inputs.github-repo-name }}" /d:sonar.scm.revision=$GITHUB_SHA /d:sonar.token=${{ inputs.sonar-token }} /d:sonar.host.url=https://sonar.dev-internal.patriotsoftware.com /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.verbose=false
      shell: bash

    - name: Project Build
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }} 
      run: dotnet build  
      shell: bash
      
    - name: Run Tests and Code Coverage
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }} 
      run: |        
        echo "running dotnet tests and code coverage....."
        dotnet tool update -g dotnet-coverage
        export PATH=$PATH:$HOME/.dotnet/tools
        export LOCAL_RUNSETTINGS=${{ inputs.local-runsettings-path }}
        . ~/.bashrc
        echo "local.runsettings: $LOCAL_RUNSETTINGS"
        if [ $LOCAL_RUNSETTINGS == "NONE" ]; then
          echo "No local.runsettings file run."
          dotnet-coverage collect 'dotnet test --logger "trx;LogFileName=test-results.trx" --verbosity minimal --configuration Release --filter TestCategory!="Smoke"' -f xml -o 'coverage.xml'
        else
          echo "Using $LOCAL_RUNSETTINGS"
          dotnet-coverage collect 'dotnet test --logger "trx;LogFileName=test-results.trx" --verbosity minimal --configuration Release --filter TestCategory!="Smoke" --settings:${{ inputs.local-runsettings-path }}' -f xml -o 'coverage.xml'
        fi        
      shell: bash

    - name: Smoke Tests
      if: ${{ inputs.smoke-runsettings-path != 'NONE' && always() }}
      run: |
        export SMOKE_RUNSETTINGS=${{ inputs.smoke-runsettings-path }}
        echo "running dotnet smoke tests using $SMOKE_RUNSETTINGS"
        dotnet test --logger 'trx;LogFileName=smoke-test-results.trx' --configuration Release --verbosity minimal --filter "TestCategory=Smoke|TestCategory=SmokeAndIntegration" --settings:${{ inputs.smoke-runsettings-path }}
      shell: bash

    - name: Sonarqube end
      run: |
        export PATH=$PATH:$HOME/.dotnet/tools
        . ~/.bashrc
        dotnet sonarscanner end /d:sonar.token="${{ inputs.sonar-token }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash

    - name: Where Am I
      run: |
        echo "List Files/Directories"
        ls
      shell: bash

    - uses: actions/upload-artifact@v3
      if: ${{ inputs.upload-sonar-results == true }}
      with:
        name: sonar-report
        path: .sonarqube/out/.sonar/report-task.txt

    - name: Output Docker Container Logs
      uses: jwalton/gh-docker-logs@v2
      if: ${{ inputs.use-dependencies == true && always() }}

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Project Validation Test Results            
        path: test/**/TestResults/**/test-results.trx
        reporter: dotnet-trx

    - name: Stop Containerized Dependencies
      if: ${{ inputs.use-dependencies  == true && always() }}
      run: |
        echo "Stopping Docker Containers"
        docker-compose -f ${{inputs.docker-compose-file-path}} down -v --remove-orphans
      shell: bash

    - name: SonarQube Code Coverage Results
      run: |
        export BRANCH_NAME=${GITHUB_REF#refs/heads/} 
        export REPO_NAME=${{ inputs.github-repo-name }}
        echo "SonarQube Code Coverage Results: https://sonar.dev-internal.patriotsoftware.com/dashboard?branch=$BRANCH_NAME&id=SynergyDataSystems_$REPO_NAME"
      shell: bash
